import "./globals.css";
import { Noto_Sans_KR } from 'next/font/google';

// component
import Header from "@/components/Header"
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const NotoSansKR = Noto_Sans_KR({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-Noto_Sans_KR'
});

export const metadata = {
  title: "Create Next App",
  description : "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`{$NotoSansKR.variable}`}>
      <body className={NotoSansKR.variable}>
          <Header />
          <StairTransition />
          <PageTransition> 
            {children}
          </PageTransition>
      </body>
    </html>
  );
}